services:
  deno:
    build:
      dockerfile: deno.Dockerfile
  go:
    build:
      dockerfile: go.Dockerfile
  uv:
    build:
      dockerfile: uv.Dockerfile
  php:
    build:
      dockerfile: php.Dockerfile
  node:
    build:
      dockerfile: node.Dockerfile
  bun:
    build:
      dockerfile: bun.Dockerfile
  dotnet:
    build:
      dockerfile: dotnet.Dockerfile
  julia:
    build:
      dockerfile: julia.Dockerfile
  rust:
    build:
      dockerfile: rust.Dockerfile
  haskell:
    build:
      dockerfile: haskell.Dockerfile
  ruby:
    build:
      dockerfile: ruby.Dockerfile
  nim:
    build:
      dockerfile: nim.Dockerfile
  zig:
    build:
      dockerfile: zig.Dockerfile
  gcc:
    build:
      dockerfile: gcc.Dockerfile
  swift:
    build:
      dockerfile: swift.Dockerfile
  clang:
    build:
      dockerfile: clang.Dockerfile
  msvc:
    build:
      dockerfile: msvc.Dockerfile
  c3:
    build:
      dockerfile: c3.Dockerfile
  odin:
    build:
      dockerfile: odin.Dockerfile
  gleam:
    build:
      dockerfile: gleam.Dockerfile
  elixir:
    build:
      dockerfile: elixir.Dockerfile
  erlang:
    build:
      dockerfile: erlang.Dockerfile
