name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: docker/setup-buildx-action@v3

      - name: Build toolchains
        uses: docker/bake-action@v7
        with:
          files: docker/compose.yaml
          push: false
          load: false
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
